### ISSUE TITLE
Incomplete debug info being captured

### ISSUE THREAD

**Issue by ndtreviv** [slhck/ffmpeg-debug-qp#12]
When I run this against a video that I scraped from Periscope (just as an example), it doesn't get all of the debug information on Linux (Ubuntu 16.04, ffmpeg 4.1.5, 4.2.2, 2.x).

When I produce the debug file on my Mac (frames_local.txt), the occurrence of "New frame" count is 31,765, but on Ubuntu (frames_server.txt) it is 16,951. The Mac version is actually correct.

Is there some sort of size limitation? I'm not sure what's going on here, but I really need a work around.

The debug output on my Mac is ~640M, but on Ubuntu was only ~333M

I can send the files if you need them.

[frames_local.txt](https://github.com/slhck/ffmpeg-debug-qp/files/4254617/frames_local.txt)
[frames_server.txt](https://github.com/slhck/ffmpeg-debug-qp/files/4254620/frames_server.txt)

**Comment by slhck** [comment]
I guess I can test with my own sample file. I have both Ubuntu and macOS available. Which ffmpeg libraries are you using on Ubuntu – the ones installed via `apt`? And for macOS, are you using the Homebrew version?

**Comment by ndtreviv** [comment]
Mac: homebrew, details being:
```
ffmpeg version 4.1.1 Copyright (c) 2000-2019 the FFmpeg developers
  built with Apple LLVM version 10.0.0 (clang-1000.11.45.5)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.1.1 --enable-shared --enable-pthreads --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags='-I/Library/Java/JavaVirtualMachines/openjdk-11.0.2.jdk/Contents/Home/include -I/Library/Java/JavaVirtualMachines/openjdk-11.0.2.jdk/Contents/Home/include/darwin' --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libmp3lame --enable-libopus --enable-librubberband --enable-libsnappy --enable-libtesseract --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librtmp --enable-libspeex --enable-videotoolbox --disable-libjack --disable-indev=jack --enable-libaom --enable-libsoxr
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
```

Ubuntu 16.04 I've tried the default, which is:

```
ffmpeg version 2.8.15-0ubuntu0.16.04.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.10) 20160609
  configuration: --prefix=/usr --extra-version=0ubuntu0.16.04.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...
```

And 4.2.2 installed via instructions here: https://tecadmin.net/install-ffmpeg-on-linux/

And 4.1.5 which I downloaded from source and installed myself, details being:
```
ffmpeg version 4.1.5 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.12) 20160609
  configuration: 
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
```

The video I used is this one: https://www.periscope.tv/w/1BRKjrdvNBBKw (just a random download) which I obtained using youtube-dl.

**Comment by ndtreviv** [comment]
One other teeny eensy squeensy thing (😳) I changed the tool debug setting to be 56 instead of 48, because I also wanted macroblock type, segmentation and interlaced values.

You can see the change in a branch on my fork, here: https://github.com/CameraForensics/ffmpeg-debug-qp/tree/as-a-tool lines 183 and 184, being:
```
        av_log_set_level(56/*48*/);
        video_dec_ctx->debug = 56/*48*/;
```

**Comment by ndtreviv** [comment]
I'm wondering if it's related to the size of the output being generated, and may not be picked up when testing against a short video.

**Comment by slhck** [comment]
Thanks for the hint about your fork. For our primary use cases we want to somewhat limit the amount of info that is output (as the generated files are huge), but if there was a CLI switch to enable the additional output, I could consider merging your changes back into this codebase.

> I'm wondering if it's related to the size of the output being generated, and may not be picked up when testing against a short video.

Certainly there cannot be more "new frame" occurrences than what is actually present in the bitstream. I will investigate in the coming days, currently a bit away from the keyboard.

**Comment by ndtreviv** [comment]
Ok. Thanks! Just a a tip, the linux output is missing all of the `nal_unit_type` outputs, and outputs the second frame as being:
```
[h264 @ 0x17acfc0] New frame, type: B                                                                                                                                                     
[h264 @ 0x17acfc0] 24d+ 24d+ 24d+ 24d+ 24d+ 24d+ 24d+ 24d+ 24d+ 24d+ 24d+ 24d+ 24d+ 24d+ 24d+ 24d+ 24d+ 24d+ 24d+ 24d+ 24d+ 24d+ 24d+ 24d+ 24d+ 24d+ 24d+ 24d+ 24d+ 24d+ 24d+ 24d+ 24d+ 24d+ 24d+ 24d+ 24d+ 
24d+ 24d+ 24d+ 24d+ 24d+ 24d+ 24d+ 24d+ 24d+ 24d+ 24d+ 24d+ 24d+ 24d+ 24d+ 24d+ 24d+ 24d+ 24d+ 24d+ 24d+ 24d+ 24d+ 24d+ 24d+ 24d+ 24d+ 24d+ 24d+ 24d+ 24d+ 24d+ 24d+ 24d+ 24d+ 24d+ 24d+ 24d+ 24d+ 24d+ 24d+
 24d+ 24d+ 
```

But on the Mac it is:
```
[h264 @ 0x7ff7f2015e00] New frame, type: B
[h264 @ 0x7ff7f2015e00] 24d  24d| 24d  24d  24d  24d  24d  24d  24d  24d  24d  24d  24d  24d  24d  24d  24d  24d  24d  24d  24d  24d  24d  24d  24d  24d  24d  24d  24d  24d  24d  24d  24d  24d  24d  24d  
24d- 24d  24d  24d- 24d  24d  24d| 24d  24d  24d  24d  24d  24d| 24d  24d  24d  24d  24d  24d  24d  24d  24d  24d  24d  24d  24d  24d  24d  24d  24d  24d  24d  24d  24d  24d- 24d- 24d| 24d  24d  24d- 24d
 24d| 24d  24d
```

**Comment by ndtreviv** [comment]
Sorry for spamming with comments, but it turns out that if I return the debug level to 48 it correctly identifies the frames. So it must be related to the size of the output or something.

**Comment by slhck** [comment]
Yeah, the output parsing is quite ugly, to be honest, so I can imagine that a change in output format can break the functionality. There might be a better way to parse the output log in a stateful manner (i.e., did a new frame arrive? If yes, continue and parse its properties, etc.).

**Comment by ndtreviv** [comment]
I think I've fixed it like this:
```
        av_log_set_level(48);
        video_dec_ctx->debug = 56;
```

**Comment by slhck** [comment]
Ok, I guess we can close this issue then, since it affects your branch of the software (with the additional output info)?

As mentioned above, I would be interested in adding this feature to my repo based on an optional switch.

**Comment by ndtreviv** [comment]
Yeah, I'm happy to put in an optional switch, but if you look at the branch that I've been working on (`as-a-tool`) it works in a different way than yours. For example, you give it a video file, and it will generate the debug output and then parse it without requiring manual intervention to perform them as separate steps.

Also it produces json, rather than ldjson. Take a closer look at the README on the `as-a-tool` branch of the fork. If you're still happy with it, then I'll add the switch.

**Comment by slhck** [comment]
I see. It actually makes sense to combine it like that (Python calling the C code), but I'm not sure if it's easy to work with the two diverging code bases. You don't have to add a switch — I can just come back on this once I have more time and see if I can merge your additions. Maybe there will be another switch for JSON vs. LDJSON output (we need the latter for some internal tools).

**Comment by lars18th** [comment]
>Maybe there will be another switch for JSON vs. LDJSON output (we need the latter for some internal tools).

For me this is relevant too. So, please include a swtich option to select between the two formats.

Thank you for contributing to this useful tool.
Regards.

**Comment by ndtreviv** [comment]
It seems I spoke too soon. I processed ~75 videos with the updated code, and the frame types are still incorrect on debug.

For example, video: https://periscope.tv/w/1DXGypVBrpVKM

The 4th frame with the debug tool (your code, not my mods) reports as being a B frame, when actually it is a P frame.

Command that I used to extract the frames:

```
ffmpeg -i video.mp4 -vsync 0 -qscale 2 -f image2 frames/%05d.jpeg
```

In the meantime I'll work on those switches.

**Comment by ndtreviv** [comment]
I've hidden the functionality behind switches on the example.py file now:

```
usage: example.py [-h] [-o OUTPUT] [-f] [-of OUTPUT_FORMAT] [-p PATH_TO_TOOL]
                  [-m | -a]
                  video

Parse QP values from ffmpeg-debug-qp

positional arguments:
  video                 Video file to generate output for

optional arguments:
  -h, --help            show this help message and exit
  -o OUTPUT, --output OUTPUT
                        Output file (defaults to LD-JSON)
  -f, --force           Overwrite output
  -of OUTPUT_FORMAT, --output-format OUTPUT_FORMAT
                        Output format, one of: ld-json (default), json or csv
  -p PATH_TO_TOOL, --path-to-tool PATH_TO_TOOL
                        Path to ffmpeg-debug-qp (defaults to /usr/local/bin/)
  -m, --include-macroblock-data
                        Include macroblock-level data, such as: type,
                        interlaced and segmentation
  -a, --compute-averages-only
                        Only compute the frame-average QPs
```

There is a breaking change in that, currently, if you just want the average it outputs it under a `qpValues` heading, but my version outputs it under a `qpAvg` heading.

`qpValues` is reserved for the macroblock QP values which are output in the absence of a `-a` switch. If the `-m` switch is included, the other macroblock data is also output.

I'll open a PR.

**Comment by lars18th** [comment]
Hi @ndtreviv ,

Thank you for this PR. However, I see that you don't have considered the MPEG-2 compatibility:
https://github.com/slhck/ffmpeg-debug-qp/pull/13/files#diff-340fdf32c1c733cb94cc76b487a2202bR99

Please, check my PR adding it. I'm sure it will be very easy to include it for you:
https://github.com/slhck/ffmpeg-debug-qp/pull/11/files

I hope you upgrade your PR.
Regards.

**Comment by ndtreviv** [comment]
> Hi @ndtreviv ,
> 
> Thank you for this PR. However, I see that you don't have considered the MPEG-2 compatibility:
> https://github.com/slhck/ffmpeg-debug-qp/pull/13/files#diff-340fdf32c1c733cb94cc76b487a2202bR99
> 
> Please, check my PR adding it. I'm sure it will be very easy to include it for you:
> https://github.com/slhck/ffmpeg-debug-qp/pull/11/files
> 
> I hope you upgrade your PR.
> Regards.

Hi @lars18th - consider it done!

**Comment by ndtreviv** [comment]
Soooo...not being particularly offay with c++, I compared the code in ffmpeg_debug_qp.c with ffmpeg's demuxing_decoding.c file, and made some mods accordingly.

After running it on Ubuntu like the others with the test video referenced above, it has extracted the right amount of frame, and the frames appear to be the correct type.

Can you review the code on this `bug-fixing` branch here: https://github.com/CameraForensics/ffmpeg-debug-qp/blob/bug-fixing/ffmpeg_debug_qp.c
and see if it all lines up?

**Comment by slhck** [comment]
It seems to work for me as well, but I only tested under Linux. I created a PR here: https://github.com/slhck/ffmpeg-debug-qp/pull/17 – I just rebased your commits on top of the current master. If you are fine with it I can merge it into this repo's master.

**Comment by slhck** [comment]
I merged the PR as the code seems to run fine. Thanks for the PR! You probably want to rebase your fork with the current master.

**Comment by ndtreviv** [comment]
Awesome - thanks!

**Comment by ndtreviv** [comment]
FYI This still doesn't work for mkv files for some reason. 🤔 Must be environment based, because it works on my laptop, but not on ubuntu...

It extracts the data, but the frames are the wrong kind again, so there must be a difference in the decoding/demuxing modules.

**Comment by lars18th** [comment]
> FYI This still doesn't work for mkv files for some reason.  Must be environment based, because it works on my laptop, but not on ubuntu...

Then capture the datalog file and share it. I'm sure it will be easy to fix it.

Regards.

**Comment by ndtreviv** [comment]
Also some MP4s. I'll try and get the debug from my laptop and ubuntu so they can be compared

**Comment by ndtreviv** [comment]
Sorry, I was wrong. There was something wrong on my end. It's only webm files that it doesn't work for, and. I guess that's because they need a different codec?

**Comment by slhck** [comment]
Yes, in WebM files, you'd typically find VP8 or VP9-encoded video. The decoders for those do not support the same debug options that we're using for MPEG video codecs (H.264, MPEG-2).

I think we could add a check for the codecs to make sure the user doesn't try to run this on unsupported files.
